"""
Schema definitions
"""
from app.schemas.common import (
    Response,
    ResponseBase,
    PaginationParams,
    PaginatedData,
    PaginatedResponse,
)
from app.schemas.member import (
    MemberBase,
    MemberCreate,
    MemberRegister,
    MemberUpdate,
    MemberStatusUpdate,
    MemberInfo,
    MemberBrief,
    Token,
    TokenData,
    LoginRequest,
    LoginResponse,
    PasswordChange,
)
from app.schemas.project import (
    ProjectBase,
    ProjectCreate,
    ProjectUpdate,
    ProjectMemberAdd,
    ProjectMemberInfo,
    ProjectInfo,
    ProjectDetail,
    ProjectBrief,
    TaskStats,
)
from app.schemas.meeting import (
    MeetingBase,
    MeetingCreate,
    MeetingUpdate,
    MeetingInfo,
    MeetingDetail,
    MeetingBrief,
)
from app.schemas.task import (
    VALID_TASK_STATUSES,
    STATUS_TRANSITIONS,
    TaskStakeholderAdd,
    TaskStakeholderInfo,
    TaskStatusChange,
    TaskStatusHistoryInfo,
    TaskBase,
    TaskCreate,
    TaskUpdate,
    TaskInfo,
    TaskDetail,
    TaskBrief,
)
from app.schemas.daily_log import (
    WorkLogBase,
    WorkLogCreate,
    WorkLogUpdate,
    WorkLogInfo,
    DailySummaryBase,
    DailySummaryCreate,
    DailySummaryInfo,
    DailyReportInfo,
    DailyReportListItem,
    QuickDailyReportCreate,
    WorkHoursSummary,
)
from app.schemas.weekly_report import (
    PersonalWeeklyReportRequest,
    ProjectWeeklyReportRequest,
    WeeklyReportUpdate,
    WeeklyReportInfo,
    WeeklyReportDetail,
    WeeklyReportListItem,
)
from app.schemas.notification import (
    NotificationInfo,
    UnreadCountResponse,
    NotificationListResponse,
    MarkReadRequest,
)
from app.schemas.invitation_code import (
    InvitationCodeCreate,
    InvitationCodeValidate,
    InvitationCodeInfo,
    InvitationCodeBrief,
)

__all__ = [
    # Common
    "Response",
    "ResponseBase", 
    "PaginationParams",
    "PaginatedData",
    "PaginatedResponse",
    # Member
    "MemberBase",
    "MemberCreate",
    "MemberRegister",
    "MemberUpdate",
    "MemberStatusUpdate",
    "MemberInfo",
    "MemberBrief",
    "Token",
    "TokenData",
    "LoginRequest",
    "LoginResponse",
    "PasswordChange",
    # Project
    "ProjectBase",
    "ProjectCreate",
    "ProjectUpdate",
    "ProjectMemberAdd",
    "ProjectMemberInfo",
    "ProjectInfo",
    "ProjectDetail",
    "ProjectBrief",
    "TaskStats",
    # Meeting
    "MeetingBase",
    "MeetingCreate",
    "MeetingUpdate",
    "MeetingInfo",
    "MeetingDetail",
    "MeetingBrief",
    # Task
    "VALID_TASK_STATUSES",
    "STATUS_TRANSITIONS",
    "TaskStakeholderAdd",
    "TaskStakeholderInfo",
    "TaskStatusChange",
    "TaskStatusHistoryInfo",
    "TaskBase",
    "TaskCreate",
    "TaskUpdate",
    "TaskInfo",
    "TaskDetail",
    "TaskBrief",
    # Daily Log
    "WorkLogBase",
    "WorkLogCreate",
    "WorkLogUpdate",
    "WorkLogInfo",
    "DailySummaryBase",
    "DailySummaryCreate",
    "DailySummaryInfo",
    "DailyReportInfo",
    "DailyReportListItem",
    "QuickDailyReportCreate",
    "WorkHoursSummary",
    # Weekly Report
    "PersonalWeeklyReportRequest",
    "ProjectWeeklyReportRequest",
    "WeeklyReportUpdate",
    "WeeklyReportInfo",
    "WeeklyReportDetail",
    "WeeklyReportListItem",
    # Notification
    "NotificationInfo",
    "UnreadCountResponse",
    "NotificationListResponse",
    "MarkReadRequest",
    # Invitation Code
    "InvitationCodeCreate",
    "InvitationCodeValidate",
    "InvitationCodeInfo",
    "InvitationCodeBrief",
]
